function(run_case name expected_status)
    execute_process(
        COMMAND "${PULSE_BINARY}" ${ARGN}
        RESULT_VARIABLE actual_status
        OUTPUT_VARIABLE output
        ERROR_VARIABLE errors
    )
    if(NOT "${actual_status}" STREQUAL "${expected_status}")
        message(FATAL_ERROR "${name}: expected status ${expected_status}, got ${actual_status}: ${errors}")
    endif()
    if(expected_status EQUAL 0)
        if(NOT errors STREQUAL "")
            message(FATAL_ERROR "${name}: unexpected stderr: ${errors}")
        endif()
        if(name STREQUAL "help" OR name STREQUAL "--help")
            if(NOT output MATCHES "v0.1.3" OR NOT output MATCHES "Usage:" OR
               NOT output MATCHES "--interval" OR NOT output MATCHES "pulse stats")
                message(FATAL_ERROR "${name}: missing help content")
            endif()
        elseif(name STREQUAL "version")
            if(NOT output STREQUAL "Pulse v0.1.3\n")
                message(FATAL_ERROR "${name}: wrong version: ${output}")
            endif()
        else()
            foreach(label CPU TEMP MEMORY DISK GPU)
                if(NOT output MATCHES "${label}[ ]+.+")
                    message(FATAL_ERROR "${name}: missing ${label} row")
                endif()
            endforeach()
        endif()
    else()
        if(NOT output STREQUAL "")
            message(FATAL_ERROR "${name}: unexpected stdout: ${output}")
        endif()
        if(name STREQUAL "invalid")
            set(expected_error "Pulse: unknown command 'bogus'. Run 'pulse help' for usage.")
        elseif(name STREQUAL "unsafe")
            set(expected_error "Pulse: unknown command '?[31m'. Run 'pulse help' for usage.")
            if(errors MATCHES "${escape}")
                message(FATAL_ERROR "${name}: terminal control escaped into stderr")
            endif()
        elseif(name MATCHES "^interval")
            set(expected_error "Pulse: interval must be a number from 0.25 to 60 seconds.")
        else()
            set(expected_error "Pulse: too many arguments. Run 'pulse help' for usage.")
        endif()
        string(FIND "${errors}" "${expected_error}" position)
        if(position EQUAL -1)
            message(FATAL_ERROR "${name}: missing useful error: ${errors}")
        endif()
    endif()
endfunction()

run_case(help 0 help)
run_case(--help 0 --help)
run_case(version 0 --version)
run_case(invalid 2 bogus)
string(ASCII 27 escape)
run_case(unsafe 2 "${escape}[31m")
run_case(extra 2 stats extra)
run_case(interval_missing 2 -i)
run_case(interval_zero 2 --interval 0)
run_case(interval_below_minimum 2 --interval 0.249)
run_case(interval_negative 2 -i -1)
run_case(interval_nan 2 --interval nan)
run_case(interval_infinite 2 -i inf)
run_case(interval_high 2 --interval 61)
run_case(interval_above_maximum 2 -i 60.01)
run_case(interval_garbage 2 stats --interval nope)
run_case(interval_suffix 2 stats -i 0.5oops)
run_case(interval_duplicate 2 -i 1 -i 1)
